apiVersion: v1
kind: Service
metadata:
  name: udagram-api-users
  labels:
    app: udagram-api-users
spec:
  type: LoadBalancer
  selector:
    app: udagram-api-users
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080