apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: davaliitos/udagram-api-users:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"  
        env:
        - name: POSTGRES_USERNAME
          value: udagramfernando
        - name: POSTGRES_PASSWORD
          value: udagramfernando
        - name: POSTGRES_DATABASE
          value: udagramfernandodev
        - name: POSTGRES_HOST
          value: udagramfernando.cezqzwxgzgvo.us-east-1.rds.amazonaws.com
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_PROFILE
          value: default
        - name: AWS_MEDIA_BUCKET
          value: udagram-fdavalos-dev
        - name: JWT_SECRET
          value: Davtid81_
        - name: URL
          value: http://a4ba78975cd0e4ef183cc1ac977c2dae-407749927.us-east-1.elb.amazonaws.com:8100
        ports:
        - containerPort: 80