version: "3.8"
services:
  udagram-api-users:
    build : 
      context: ./api-users
    image: davaliitos/udagram-api-users
  udagram-api-feed:
    build : 
      context: ./api-feed
    image: davaliitos/udagram-api-feed
  udagram-frontend:
    build : 
      context: ./frontend
    image: davaliitos/udagram-frontend

