apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  namespace: frontend
  labels:
    app: udagram-frontend
spec:
  type: NodePort
  selector:
    app: udagram-frontend
  ports:
    - name: "8100"
      port: 8100
      nodePort: 30150